name: 'Duplicate Logic Detector'
description: 'Automatically detect duplicate logic in Python code.'
author: 'ArthurMor4is'

branding:
  icon: 'search'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  
  pr-number:
    description: 'Pull request number'
    required: false
    default: ${{ github.event.number }}
  
  repository:
    description: 'Repository name (owner/repo)'
    required: false
    default: ${{ github.repository }}
  
  base-ref:
    description: 'Base reference for comparison'
    required: false
    default: ${{ github.base_ref }}
  
  head-ref:
    description: 'Head reference for comparison'
    required: false
    default: ${{ github.head_ref }}
  
  
  
  post-comment:
    description: 'Whether to post findings as PR comment'
    required: false
    default: 'true'
  
  fail-on-duplicates:
    description: 'Whether to fail the action if high-confidence duplicates are found'
    required: false
    default: 'false'
  

outputs:
  duplicates-found:
    description: 'Whether any duplicates were found'
    value: ${{ steps.detect.outputs.duplicates_found }}
  
  match-count:
    description: 'Number of duplicate matches found'
    value: ${{ steps.detect.outputs.match_count }}
  
  
  report-path:
    description: 'Path to the generated report file'
    value: ${{ steps.detect.outputs.report_path }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      shell: bash
      run: ${{ github.action_path }}/scripts/action/install-dependencies.sh
    
    - name: Copy detection scripts
      shell: bash
      run: |
        # Copy the detection script from the action
        cp ${{ github.action_path }}/scripts/duplicate_logic_detector.py ./
        chmod +x duplicate_logic_detector.py
    
    - name: Get changed files
      id: changed-files
      shell: bash
      env:
        BASE_REF: ${{ inputs.base-ref }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
      run: ${{ github.action_path }}/scripts/action/get-changed-files.sh
    
    - name: Run duplicate logic detection
      id: detect
      shell: bash
      env:
        CHANGED_FILES: ${{ steps.changed-files.outputs.changed_files }}
        BASE_SHA: ${{ steps.changed-files.outputs.base_sha }}
        HEAD_SHA: ${{ steps.changed-files.outputs.head_sha }}
        PR_NUMBER: ${{ inputs.pr-number }}
        REPOSITORY: ${{ inputs.repository }}
      run: ${{ github.action_path }}/scripts/action/run-detection.sh
    
    - name: Upload analysis results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: duplicate-logic-analysis-${{ github.run_id }}
        path: |
          duplicate-logic-report.json
          duplicate-logic-report.md
        retention-days: 30
        if-no-files-found: ignore
    
    - name: Comment on PR
      if: steps.detect.outputs.duplicates_found == 'true' && inputs.post-comment == 'true' && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const postComment = require('${{ github.action_path }}/scripts/action/post-comment.js');
          await postComment({github, context, core});
    
    - name: Fail if duplicates found
      if: steps.detect.outputs.duplicates_found == 'true' && inputs.fail-on-duplicates == 'true'
      shell: bash
      run: |
        echo "❌ Duplicate logic detected!"
        echo "Found ${{ steps.detect.outputs.match_count }} duplicate matches"
        echo "Please review the duplicate logic report and consider refactoring before merging."
        exit 1
