name: Django Code Quality

on:
  pull_request:
    paths: ['**/*.py']

jobs:
  duplicate-logic:
    name: Check for Duplicate Logic
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Detect Duplicate Logic
        uses: your-org/duplicate-logic-detector-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          include-patterns: '["myapp/**/*.py", "utils/**/*.py", "models/**/*.py"]'
          exclude-patterns: '["migrations/**", "tests/**", "manage.py", "settings/**"]'
          similarity-threshold: '0.75'
          fail-on-duplicates: true
