name: Django Code Quality

on:
  pull_request:
    paths: ['**/*.py']

jobs:
  duplicate-logic:
    name: Check for Duplicate Logic
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Detect Duplicate Logic
        uses: ArthurMor4is/duplicate-logic-detector-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-duplicates: true
          similarity-method: levenshtein_norm  # More strict for production code
