name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## What's Changed
            
            See the [CHANGELOG](CHANGELOG.md) for detailed changes.
            
            ## Usage
            
            ```yaml
            - name: Detect Duplicate Logic
              uses: arthurfernandesdemorais/duplicate-logic-detector-action@${{ github.ref }}
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
            ```
          draft: false
          prerelease: false

  update-major-tag:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update major version tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          # Extract major version (e.g., v1.2.3 -> v1)
          TAG=${GITHUB_REF#refs/tags/}
          MAJOR_VERSION=$(echo $TAG | cut -d. -f1)
          
          # Create or update major version tag
          git tag -fa $MAJOR_VERSION -m "Update $MAJOR_VERSION to $TAG"
          git push origin $MAJOR_VERSION --force
